apiVersion: v1
kind: Service
metadata:
  name: capstone
  labels:
    app: capstone
spec:
  selector:
    app: capstone
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: LoadBalancer
