apiVersion: v1
kind: Service
metadata:
  name: capstone
  labels:
    app: demo
spec:
  selector:
    app: capstone
    type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
